version: "3.3"

services:
  netskope-ui:
    build:
      context: ./app
    ports:
      - "3000:3000"
    container_name: netskope-ui
    stdin_open: true
    volumes:
      - ./app:/usr/src/app/app
      - /usr/src/app/app/node_modules
